baseURL = "https://frosty-haibt-e6eb71.netlify.com/"
languageCode = "en-us"
theme = "hyde"
title = "My New Hugo Site"
[Menus]
main = [
    {Name = "Posts", URL = "/posts"}
]
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""
